nome = input ("Digite seu nome: ")
idade = input ("Digite sua idade : ")
cor_favorita = input ("Digite sua cor favorita: ")
responsavel = input ("Digite o nome do seu responsavel: ")
escola = input ("Digite sua escola: ")
print (f"\n Oi meu nome é {nome}")
print (f"\n Minha idade é de {idade} anos")
print (f"\n Minha cor favorita é {cor_favorita}")
print (f"\n O nome do meu responsavel é {responsavel}")
print (f"\n Eu estudo no colegio {escola}")
